version: '3.3'

services:
  postgres:
    image: postgres:13
    restart: "no"
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=lite_thinking
      - POSTGRES_USER=andres
      - POSTGRES_PASSWORD=a1b2c3d4e5
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: "no"
    volumes: [./servers.json:/pgadmin4/servers.json]
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - POSTGRES_PASSWORD=a1b2c3d4e5
      - POSTGRES_USER=andres
      - POSTGRES_DB=lite_thinking
    ports:
      - 5050:80

networks:
  default:
    name: database_network
